image: node:18.20.4
clone:
  depth: full
options:
  docker: true
  size: 2x
pipelines:
  branches:
    "{master}":
      - step:
          name: Run Unit tests
          script:
            - npm i --legacy-peer-deps;
            - npm run coverage;
          artifacts:
            - coverage/**
          services:
            - docker
          size: 2x
      - step:
          name: Run Unit tests
          script:
            - npm i --legacy-peer-deps;
            - npm run coverage;
          artifacts:
            - coverage/**
          services:
            - docker
          size: 2x
  pull-requests:
    "**":
      - step:
          name: Run Unit tests
          script:
            - npm i --legacy-peer-deps;
            - npm run coverage;
          artifacts:
            - coverage/**
          services:
            - docker
          size: 2x
definitions:
  services:
    docker:
      memory: 4096
