#!/bin/bash

VERSION=$1
echo "Incrementing version to $VERSION"

git checkout customer
git pull

sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/g" package.json
sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/g" app/manifest.json

git commit -a -m "Hook updating version"