#!/bin/bash

VERSION=$1
echo "Incrementing version to $VERSION"

git checkout customer
git pull

sed -i".original" "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/g" package.json
sed -i".original" "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/g" app/manifest.json

rm package.json.original app/manifest.json.original

git commit -a -m "Hook updating version"